# Generated by Django 5.2.14 on 2026-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('documentary', 'Documentary'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi')], max_length=50)),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('video_file', models.FileField(upload_to='videos/raw/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
